=== eovoc/eof-eos-validator/public/schemas/eof-eos-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "GeoJSON encoding of OGC 17-003 Earth Observation Metadata",
	"description": "Definition of EOF-EOS Metadata model derived from OGC 17-003r2.",
	"$ref": "#/definitions/EarthObservation",
	"definitions": {
		"MetadataInformation": {
			"description": "Subset of Properties",
			"type": "object",
			"properties": {
				"lang": {
					"description": "RFC3066",
					"type": "string",
					"minLength": 2,
					"maxLength": 3
				},
				"creationDate": {
					"type": "string",
					"format": "date-time"
				}
			}
		},
		"DataIdentification": {
			"description": "Subset of Properties",
			"type": "object",
			"properties": {
				"doi": {
					"type": "string"
				},
				"title": {
					"type": "string"
				},
				"date": {
					"type": "string"
				},
				"created": {
					"type": "string",
					"format": "date-time"
				},
				"additionalAttributes": {
					"type": "object",
					"minProperties": 1
				}
			},
			"required": [
				"title",
				"date", "created"
			]
		},
		"ProcessingInformation": {
			"description": "Subset of ProductInformation",
			"type": "object",
			"properties": {
				"resourceLineage": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "mdj.json#/definitions/LI_Lineage"
					}
				},
				"processingLevel": {
					"type": "string",
					"enum": [
						"1A",
						"1B",
						"1C",
						"2",
						"2A",
						"3"
					]
				},
				"processorName": {
					"type": "string"
				},
				"processorVersion": {
					"type": "string"
				},
				"processingCenter": {
					"type": "string"
				},
				"processingDate": {
					"type": "string",
					"format": "date-time"
				},
				"processingMode": {
					"type": "string"
				},
				"compositeType": {
					"type": "string"
				},
				"format": {
					"type": "string"
				},
				"productContentsType": {
					"type": "string"
				},
				"processingMethod": {
					"type": "string"
				},
				"processingMethodVersion": {
					"type": "string"
				}
			}
		},
		"Point": {
			"title": "Point",
			"type": "object",
			"properties": {
				"coordinates": {
					"title": "gj:coordinates",
					"description": "One position (longitude, lattitude)",
					"type": "array",
					"minItems": 2,
					"maxItems": 2,
					"items": {
						"type": "number"
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"Point"
					]
				}
			},
			"required": [
				"coordinates",
				"type"
			],
			"additionalProperties": false
		},
		"MultiPoint": {
			"title": "point",
			"type": "object",
			"properties": {
				"coordinates": {
					"title": "gj:coordinates",
					"description": "Array of positions",
					"type": "array",
					"minItems": 1,
					"items": [
						{
							"description": "One position",
							"type": "array",
							"minItems": 2,
							"maxItems": 2,
							"items": {
								"type": "number"
							}
						}
					],
					"additionalItems": false
				},
				"type": {
					"type": "string",
					"enum": [
						"MultiPoint"
					]
				}
			},
			"required": [
				"coordinates",
				"type"
			],
			"additionalProperties": false
		},
		"LineString": {
			"title": "LineString",
			"type": "object",
			"properties": {
				"coordinates": {
					"title": "coordinates",
					"description": "Array of positions",
					"type": "array",
					"minItems": 2,
					"items": {
						"description": "One position",
						"type": "array",
						"minItems": 2,
						"maxItems": 2,
						"items": {
							"type": "number"
						}
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"LineString"
					]
				}
			},
			"required": [
				"coordinates",
				"type"
			],
			"additionalProperties": false
		},
		"MultiLineString": {
			"title": "MultiLineString",
			"type": "object",
			"properties": {
				"coordinates": {
					"title": "coordinates",
					"description": "Array of linestring",
					"type": "array",
					"minItems": 1,
					"items": {
						"description": "Linestring, i.e. array of positions",
						"type": "array",
						"minItems": 2,
						"items": {
							"description": "Position (longitude, lattitude)",
							"type": "array",
							"minItems": 2,
							"maxItems": 2,
							"items": {
								"type": "number"
							}
						}
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"MultiLineString"
					]
				}
			},
			"required": [
				"coordinates",
				"type"
			],
			"additionalProperties": false
		},
		"Polygon": {
			"title": "Polygon",
			"type": "object",
			"properties": {
				"coordinates": {
					"title": "coordinates",
					"description": "Array of linestrings",
					"type": "array",
					"minItems": 1,
					"items": {
						"description": "Linear ring, i.e. linestring or array of positions",
						"type": "array",
						"minItems": 1,
						"items": {
							"description": "One position",
							"type": "array",
							"minItems": 2,
							"maxItems": 2,
							"items": {
								"type": "number"
							}
						}
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"Polygon"
					]
				}
			},
			"required": [
				"coordinates",
				"type"
			],
			"additionalProperties": false
		},
		"MultiPolygon": {
			"title": "MultiPolygon",
			"type": "object",
			"properties": {
				"coordinates": {
					"title": "coordinates",
					"description": "Array of Polygons",
					"type": "array",
					"minItems": 1,
					"items": {
						"description": "Array of linestrings",
						"type": "array",
						"minItems": 1,
						"items": {
							"description": "Linear ring, i.e. linestring or array of positions",
							"type": "array",
							"items": {
								"description": "One position",
								"type": "array",
								"minItems": 2,
								"maxItems": 2,
								"items": {
									"type": "number"
								}
							}
						}
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"MultiPolygon"
					]
				}
			},
			"required": [
				"coordinates",
				"type"
			],
			"additionalProperties": false
		},
		"Geometry": {
			"title": "Geometry",
			"type": "object",
			"oneOf": [
				{
					"$ref": "#/definitions/Point"
				},
				{
					"$ref": "#/definitions/MultiPoint"
				},
				{
					"$ref": "#/definitions/LineString"
				},
				{
					"$ref": "#/definitions/MultiLineString"
				},
				{
					"$ref": "#/definitions/Polygon"
				},
				{
					"$ref": "#/definitions/MultiPolygon"
				}
			]
		},
		"Links": {
			"title": "Links",
			"description": "Objects with Links grouped by \"relation\".",
			"type": "object",
			"properties": {
				"measurements": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Link"
					}
				},
				"previews": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Link"
					}
				},
				"quality": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Link"
					}
				},
				"condition": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Link"
					}
				}
				
			
			}
		},
		"Properties": {
			"title": "Properties",
			"type": "object",
			"allOf": [
				{
					"type": "object",
					"properties": {
						
						"status": {
							"type": "string",
							"enum": [
								"ACQUIRED",
								"QUALITYDEGRADED"
							]
						},
						"acquisitionInformation": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/AcquisitionInformation"
							}
						},
						"productInformation": {
							"$ref": "#/definitions/ProductInformation"
						},
						"links": {
							"$ref": "#/definitions/Links"
						}
					},
					"required": [
						"status",
						"acquisitionInformation",
						"productInformation"
					]
				},
				{
					"$ref": "#/definitions/DataIdentification"
				}
			]
		},
		"EarthObservation": {
			"description": "GeoJSON Feature",
			"type": "object",
			"properties": {
			
				"type": {
					"title": "type",
					"type": "string",
					"enum": [
						"Feature"
					]
				},
				"id": {
					"type": "string"
				},
				"geometry": {
					"oneOf": [
						{
							"$ref": "#/definitions/Geometry"
						},
						{
							"type": "null"
						}
					]
				},
				"properties": {
					"$ref": "#/definitions/Properties"
				},
				"bbox": {
					"type": "array",
					"minItems": 4,
					"maxItems": 4,
					"items": {
						"type": "number"
					}
				}
			},
			"required": [
				"type",
				"id",
				"geometry",
				"properties"
			],
			"additionalProperties": false
		},
		"Platform": {
			"type": "object",
			"minProperties": 1,
			"properties": {
				"platformShortName": {
					"type": "string"
				},
				"platformSerialIdentifier": {
					"type": "string"
				},
				"orbitType": {
					"type": "string",
					"enum": [
						"GEO",
						"LEO"
					]
				}
			},
			"required": [
				"platformShortName",
				"orbitType"
			],
			"additionalProperties": false
		},
		"Instrument": {
			"type": "object",
			"properties": {
				"sensorType": {
					"type": "string"
				},
				"instrumentShortName": {
					"type": "string"
				},
				"description": {
					"type": "string"
				}
			},
			"required": [
				"sensorType",
				"instrumentShortName"
			],
			"additionalProperties": false
		},
		"AcquisitionParameters": {
			"type": "object",
			"allOf": [
				{
					"type": "object",
					"properties": {
						"acquisitionType": {
							"type": "string",
							"enum": [
								"NOMINAL",
								"CALIBRATION",
								"OTHER"
							]
						},
						"acquisitionSubType": {
							"type": "string"
						},
						"startTimeFromAscendingNode": {
							"type": "integer",
							"minimum": 0
						},
						"completionTimeFromAscendingNode": {
							"type": "integer",
							"minimum": 0
						},
						"relativeOrbitNumber": {
							"type": "integer"
						},
						"wrsLongitude": {
							"type": "string"
						},
						"wrsLatitude": {
							"type": "string"
						},
						"tileId": {
							"type": "string"
						},
						"groundTrackUncertainty": {
							"type": "number"
						},
						"cycleNumber": {
							"type": "integer",
							"minimum": 0
						},
						"antennaLookDirection": {
							"type": "string",
							"enum": [
								"LEFT",
								"RIGHT"
							]
						},
						"acquisitionStation": {
							"$ref": "eof-eos/acquisition-station-types"
						},
						"acquisitionAngles": {
							"$ref": "#/definitions/AcquisitionAngles"
						},
						"operationalMode": {
							"type": "string"
						},
						"swathIdentifier": {
							"type": "string"
						},
						"polarisationMode": {
							"description": "Sar",
							"type": "string",
							"enum": [
								"S",
								"D",
								"T",
								"Q",
								"UNDEFINED"
							]
						},
						"polarisationChannels": {
							"description": "Sar",
							"type": "string"
						},
						"resolution": {
							"type": "number"
						},
						"verticalResolution": {
							"description": "Atm, Lmb",
							"type": "number"
						},
						"waveLengths": {
							"type": "array",
							"minItems": 1,
							"items": {
								"$ref": "#/definitions/WavelengthInformation"
							}
						},
						"measurementType": {
							"type": "string",
							"enum": [
								"ABSORPTION",
								"EMISSION"
							]
						},
						"dopplerFrequency": {
							"description": "Sar",
							"type": "number",
							"minimum": 0,
							"exclusiveMinimum": 0
						},
						"samplingRates": {
							"description": "Alt",
							"type": "array",
							"items": {
								"type": "number",
								"minimum": 0,
								"exclusiveMinimum": 0
							}
						}
					},
					"required": [
						"acquisitionType"
					]
				},
				{
					"$ref": "#/definitions/TemporalInformation"
				},
				{
					"$ref": "#/definitions/VerticalSpatialDomain"
				},
				{
					"$ref": "#/definitions/OrbitParameters"
				}
			]
		},
		"Link": {
			"type": "object",
			"properties": {
				"href": {
					"type": "string"
				},
				"type": {
					"type": "string"
				},
				"title": {
					"type": "string"
				},
				"length": {
					"type": "integer",
					"minimum": 0
				},
				"category": {
					"type": "string",
					"enum": [
						"THUMBNAIL",
						"QUICKLOOK",
						"ALBUM",
						"CLOUD",
						"SNOW",
						"QUALITY"
					]
				}
				
			},
			"required": [
				"href", "type", "title", "category"
			],
			"additionalProperties": false
		},
		"ProductInformation": {
			"type": "object",
			"allOf": [
				{
					"type": "object",
					"properties": {
						
						"productType": {
							"type": "string"
						},
						"size": {
							"type": "integer"
						},
					
						"qualityInformation": {
							"$ref": "#/definitions/QualityInformation"
						},
						"statusDetail": {
							"type": "string"
						},
						"timeliness": {
							"type": "string"
						},
						"referenceSystemIdentifier": {
							"type": "string"
						}
					}
				},
				{
					"$ref": "#/definitions/ProcessingInformation"
				},
				{
					"$ref": "#/definitions/CoverageDescription"
				}
			]
		},
		"AcquisitionAngles": {
			"type": "object",
			"properties": {
				"illuminationAzimuthAngle": {
					"type": "number"
				},
				"illuminationZenithAngle": {
					"type": "number"
				},
				"illuminationElevationAngle": {
					"type": "number"
				},
				"incidenceAngle": {
					"type": "number"
				},
				"minimumIncidenceAngle": {
					"type": "number"
				},
				"maximumIncidenceAngle": {
					"type": "number"
				},
				"incidenceAngleVariation": {
					"type": "number"
				},
				"acrossTrackIncidenceAngle": {
					"type": "number"
				},
				"alongTrackIncidenceAngle": {
					"type": "number"
				},
				"instrumentAzimuthAngle": {
					"type": "number"
				},
				"instrumentZenithAngle": {
					"type": "number"
				},
				"instrumentElevationAngle": {
					"type": "number"
				},
				"pitch": {
					"type": "number"
				},
				"roll": {
					"type": "number"
				},
				"yaw": {
					"type": "number"
				}
			},
			"additionalProperties": false
		},
		"QualityInformation": {
			"anyOf": [
				{
					"$ref": "dqc.json#/definitions/DataQuality"
				},
				{
					"type": "object",
					"properties": {
						"qualityStatus": {
							"type": "string",
							"enum": [
								"NOMINAL",
								"DEGRADED"
							]
						},
						"qualityDegradation": {
							"description": "Percentage",
							"type": "number"
						},
						"qualityDegradationTag": {
							"type": "string"
						},
						"qualityDegradationQuotationMode": {
							"type": "string",
							"enum": [
								"AUTOMATIC",
								"MANUAL"
							]
						}
					}
				}
			]
		},
		"CoverageDescription": {
			"description": "Subset of ProductInformation",
			"type": "object",
			"properties": {
				"cloudCover": {
					"type": "number"
				},
				"snowCover": {
					"type": "number"
				}
			}
		},
		"FeatureCollection": {
			"description": "GeoJSON FeatureCollection",
			"type": "object",
			"properties": {
				"type": {
					"type": "string",
					"enum": [
						"FeatureCollection"
					]
				},
				"bbox": {
					"type": "array"
				},
				"features": {
					"type": "array",
					"minItems": 0,
					"items": {
						"$ref": "#/definitions/EarthObservation"
					}
				}
			},
			"required": [
				"type",
				"features"
			]
		},
		"WavelengthInformation": {
			"type": "object",
			"minProperties": 1,
			"properties": {
				"discreteWavelengths": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "number",
						"minimum": 0,
						"exclusiveMinimum": 0
					}
				},
				"startWavelength": {
					"type": "number",
					"minimum": 0,
					"exclusiveMinimum": 0
				},
				"endWavelength": {
					"type": "number",
					"minimum": 0,
					"exclusiveMinimum": 0
				},
				"spectralRange": {
					"type": "string",
					"enum": [
						"INFRARED",
						"NIR",
						"SWIR",
						"MWIR",
						"LWIR",
						"FIR",
						"UV",
						"VISIBLE",
						"MICROWAVE",
						"OTHER"
					]
				},
				"wavelengthResolution": {
					"type": "number"
				}
			},
			"additionalProperties": false
		},
		"VerticalSpatialDomain": {
			"description": "Subset of AcquisitionParameters",
			"type": "object",
			"properties": {
				"highestLocation": {
					"type": "string"
				},
				"lowestLocation": {
					"type": "string"
				},
				"locationUnit": {
					"type": "string",
					"enum": [
						"bar",
						"m"
					]
				}
			}
		},
		"TemporalInformation": {
			"description": "Subset of AcquisitionParameters",
			"type": "object",
			"properties": {
				"beginningDateTime": {
					"type": "string",
					"format": "date-time"
				},
				"endingDateTime": {
					"type": "string",
					"format": "date-time"
				}
			},
			"required": [
				"beginningDateTime",
				"endingDateTime"
			]
		},
		"AcquisitionInformation": {
			"type": "object",
			"properties": {
				"platform": {
					"$ref": "#/definitions/Platform"
				},
				"instrument": {
					"$ref": "#/definitions/Instrument"
				},
				"acquisitionParameters": {
					"$ref": "#/definitions/AcquisitionParameters"
				}
			}
		},
		"Offering": {
			"title": "Offering",
			"description": "Offering as defined in OGC 14-055r2",
			"type": "object",
			"properties": {
				"code": {
					"type": "string",
					"format": "uri"
				},
				"operations": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Operation"
					}
				},
				"contents": {
					"type": "array"
				},
				"styles": {
					"type": "array"
				}
			},
			"required": [
				"code"
			]
		},
		"OrbitParameters": {
			"description": "Subset of AcquisitionParameters",
			"type": "object",
			"properties": {
				"orbitDirection": {
					"type": "string",
					"enum": [
						"ASCENDING",
						"DESCENDING"
					]
				},
				"lastOrbitDirection": {
					"type": "string",
					"enum": [
						"ASCENDING",
						"DESCENDING"
					]
				},
				"orbitDuration": {
					"type": "integer"
				},
				"ascendingNodeDate": {
					"type": "string",
					"format": "date-time"
				},
				"ascendingNodeLongitude": {
					"type": "number"
				},
				"orbitNumber": {
					"type": "integer",
					"minimum": 0
				},
				"lastOrbitNumber": {
					"type": "number"
				}
			}
		},
		"Operation": {
			"description": "OGC 14-055r2",
			"type": "object",
			"properties": {
				"code": {
					"type": "string",
					"format": "uri"
				},
				"method": {
					"type": "string",
					"enum": [
						"GET",
						"POST",
						"PUT",
						"HEAD",
						"PATCH",
						"DELETE"
					]
				},
				"type": {
					"description": "Media type",
					"type": "string"
				},
				"href": {
					"type": "string",
					"format": "uri"
				},
				"request": {
					"type": "object"
				},
				"result": {
					"type": "object"
				}
			},
			"required": [
				"code",
				"method",
				"href"
			]
		}
	}
}

=== eovoc/eof-eos-validator/tests/__fixtures__/ogc/valid-eof-eos-example.json
{
	"bbox": [
		-77.38244,
		-1.9621029,
		-76.55338,
		-0.5793365
	],
	"geometry": {
		"coordinates": [
			[
				[
					-77.38244,
					-1.8435793
				],
				[
					-76.81995,
					-1.9621029
				],
				[
					-76.55338,
					-0.6989397
				],
				[
					-77.11765,
					-0.5793365
				],
				[
					-77.38244,
					-1.8435793
				]
			]
		],
		"type": "Polygon"
	},
	"id": "BIO_FP_FD__L2A_20251006T231917_20251021T231931_C_G___M___C___T____F156_01_DIEV9F",
	"type": "Feature",
	"properties": {
		"date": "2025-10-06T23:19:17.460Z/2025-10-21T23:19:31.059Z",
		"created": "2025-10-06T23:19:17.460Z",
		"links": {} ,
		
		"productInformation": {
			"processingCenter": "Biomass CPF",
			"productVersion": "01",
			"processingLevel": "2A",
			"processingDate": "2025-11-20T20:51:15Z",
			"processorName": "Biomass L2a Processor",
			"processorVersion": "4.1.1",
			"processingMode": "OPERATIONAL",
			"productType": "FP_FD__L2A",
			
			"resourceLineage": [
				{
					"processStep": [
						{
							"description": "L2A",
							"stepDateTime": {
								"created": "2025-11-20T20:51:15Z"
							},
							"processor": [
								{
									"role": "processor",
									"party": [
										{
											"name": "Biomass CPF",
											"type": "CI_Organisation"
										}
									]
								}
							],
							"reference": [
								{
									"title": "BIOMASS Forest Disturbance Product Format Specification (BPS_FD_PFD) V3.2.1",
									"edition": "3.2.1"
								},
								{
									"title": "BIOMASS Product Performance Description (BPS_PPD)",
									"edition": "3.1.0"
								}
							],
							"source": [
								{
									"sourceCitation": {
										"title": "BIO_S2_STA__1S_20251012T231914_20251012T231935_C_G___M___C___T____F156_01_DHQZTP"
									},
									"sourceMetadata": [
										{
											"title": "BIO_S2_STA__1S_20251012T231914_20251012T231935_C_G___M___C___T____F156_01_DHQZTP",
											"onlineResource": [
												{
													"linkage": "https://catalog.maap.eo.esa.int/catalogue/BiomassLevel2aIOC/collections/items/BIO_S2_STA__1S_20251012T231914_20251012T231935_C_G___M___C___T____F156_01_DHQZTP"
												}
											]
										}
									]
								},
								{
									"sourceCitation": {
										"title": "BIO_S2_STA__1S_20251006T231917_20251006T231938_C_G___M___C___T____F156_01_DHQZSU"
									}
								},
								{
									"sourceCitation": {
										"title": "BIO_S2_STA__1S_20251021T231910_20251021T231931_C_G___M___C___T____F156_01_DHQZT9"
									}
								}
							],
							"processingInformation": {
								"softwareReference": {
									"title": "Biomass L2a Processor",
									"edition": "4.1.1"
								}
							},
							"output": [
								{
									"sourceCitation": {
										"title": "BIO_FP_FD__L2A_20251006T231917_20251021T231931_C_G___M___C___T____F156_01_DIEV9F"
									}
								}
							]
						}
					]
				}
			],
			"qualityInformation": {
				"scope": {
					"level": "dataset"
				},
				"report": [
					{
						"result": [
							{
								"valueUnit": "%",
								"type": "QuantitativeResult",
								"value": [
									0
								]
							}
						],
						"measure": {
							"measureIdentification": {
								"code": "211",
								"authority": {
									"alternateTitle": [
										"ISO"
									],
									"title": "International Organization for Standardization"
								},
								"codeSpace": "https://standards.isotc211.org/19157/-3/1/dqc/content/qualityMeasure/"
							},
							"measureDescription": "Quality degradation - rate of imperfect coverage.",
							"nameOfMeasure": [
								"MD211"
							]
						},
						"evaluationMethod": [
							{
								"type": "FullInspection",
								"evaluationMethodDescription": "Automatic quality degradation check."
							}
						],
						"type": "Omission"
					}
				]
			}
		},
			
		"title": "BIO_FP_FD__L2A_20251006T231917_20251021T231931_C_G___M___C___T____F156_01_DIEV9F",
		
		"acquisitionInformation": [
			{
				"acquisitionParameters": {
					"operationalMode": "SM",
					"acquisitionType": "NOMINAL",
					"beginningDateTime": "2025-10-06T23:19:17.460Z",
					"wrsLongitudeGrid": "NA",
					"wrsLatitudeGrid": "156",
					"swathIdentifier": "S2",
					"antennaLookDirection": "LEFT",
					"endingDateTime": "2025-10-21T23:19:31.059Z",
					"orbitDirection": "DESCENDING"
				},
				"instrument": {
					"instrumentShortName": "P-SAR",
					"sensorType": "RADAR"
				},
				"platform": {
					"platformShortName": "Biomass",
                    "orbitType": "LEO"
				}
			}
		],
		"status": "ACQUIRED",
		"additionalAttributes": {
			"refDoc": [
				"BIOMASS Forest Disturbance Product Format Specification (BPS_FD_PFD) V3.2.1",
				"BIOMASS Product Performance Description (BPS_PPD) V3.1.0"
			],
			"sourceProduct": [
				"BIO_S2_STA__1S_20251012T231914_20251012T231935_C_G___M___C___T____F156_01_DHQZTP",
				"BIO_S2_STA__1S_20251006T231917_20251006T231938_C_G___M___C___T____F156_01_DHQZSU",
				"BIO_S2_STA__1S_20251021T231910_20251021T231931_C_G___M___C___T____F156_01_DHQZT9"
			],
			"globalCoverageID": "NA",
			"tileID": "S02W078",
			"openIdConnectUrl": "https://iam.ascend.icsgate.eu/realms/esa-maap/.well-known/openid-configuration",
			"missionPhase": "COMMISSIONING",
			"basinID": "B100",
			"majorCycleID": "NA"
		}
	}
}
